### ISSUE TITLE
Why are the accuracy of multiple subtasks in this project so low?

### ISSUE THREAD

**Issue by davidzhang1987** [ga642381/SpeechPrompt-v2#2]
Hello, in the SpeechPrompt-v2 project, the results of my multiple tasks are quite different from the indicators in the paper. Could you please tell me what the problem may be? I am looking forward to your answer. 
Here are some of my task metrics:
Google Speech Commands v1 （my：94.81 VS paper：94.5%），Grabo Speech Commands（my：1.98%VS paper：92.4%），Lithuanian Speech Commands (my：42.86% VS paper：93.2%），Arabic Speech Commands（my ：89.46% VS paper：99.7%），LID_voxforge（my：32.22% VS paper：90.9%），MUStARD Dataset（my：38.41% VS paper： 55%），ESC-50（my：2.25% VS paper：9%）.

**Comment by ga642381** [comment]
Hi @davidzhang1987,

Thank you for bringing up the issue.

It appears that the most significant performance degradation is observed in **Grabo speech commands** and **Lithuanian speech commands**. Could you please provide additional information? This would help me identify the source of the bug. For example, the processed dataset, and the standard output of the training process would be helpful.

P.S. There might be some variability in the experimental results due to factors like randomness in training and data splitting. In the upcoming version of SpeechPrompt, I plan to conduct more experimental runs and report the average performance, as well as the deviations.

**Comment by davidzhang1987** [comment]
> 

Thank you for your answer, take the Grabo speech commands task as an example, SCR_grabo_ori.tar.gz is the processed dataset，output_files.tar.gz is the output files. and the SCR_grabo_speech_commands_train.log is the training log in the attachments. [Uploading SCR_grabo_speech_commands_train.log…]()
[Uploading SCR_grabo_ori.tar.gz…]()

**Comment by davidzhang1987** [comment]
restart

**Comment by davidzhang1987** [comment]
> 

Thank you for your answer, take the Grabo speech commands task as an example, SCR_grabo_ori.tar.gz is the processed dataset，output_files.tar.gz is the output files. and the SCR_grabo_speech_commands_train.log is the training log in the attachments.
[SCR_grabo_speech_commands_train.log](https://github.com/ga642381/SpeechPrompt-v2/files/12300330/SCR_grabo_speech_commands_train.log)
[output_files.tar.gz](https://github.com/ga642381/SpeechPrompt-v2/files/12300333/output_files.tar.gz)
[SCR_grabo_ori.tar.gz](https://github.com/ga642381/SpeechPrompt-v2/files/12300335/SCR_grabo_ori.tar.gz)

**Comment by davidzhang1987** [comment]
reopen
